### ISSUE TITLE
Tcomb-Form-Native module extension error w/ Testing

### ISSUE THREAD

**Issue by bartonhammond** [bartonhammond/snowflake#109]
Failure is waiting on  [https://github.com/gcanti/tcomb-form-native/issues/134]( https://github.com/gcanti/tcomb-form-native/issues/134) so the file has been renamed

 FAIL  src/components/__tests__/LoginForm-test.js (0s)
 Runtime Error
  - Error: Cannot find module './datepicker' from 'index.js'
        at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:197:17)
        at Runtime._resolveModule (node_modules/jest-runtime/build/index.js:327:32)
        at Runtime._normalizeID (node_modules/jest-runtime/build/index.js:492:31)
        at Runtime._shouldMock (node_modules/jest-runtime/build/index.js:536:27)
        at Runtime.requireModuleOrMock (node_modules/jest-runtime/build/index.js:271:14)
        at Object.<anonymous> (node_modules/tcomb-form-native/lib/templates/bootstrap/index.js:5:12)
        at Runtime._execModule (node_modules/jest-runtime/build/index.js:375:17)
        at Runtime.requireModule (node_modules/jest-runtime/build/index.js:210:14)
        at Runtime.requireModuleOrMock (node_modules/jest-runtime/build/index.js:274:19)
        at Object.<anonymous> (node_modules/tcomb-form-native/index.js:3:16)

**Comment by bartonhammond** [comment]
PR #111 fixes
