### ISSUE TITLE
npm install failed in Windows, node 7.0

### ISSUE THREAD

**Issue by yhyuan** [bartonhammond/snowflake#160]
Here is the error message. Can someone give any help? 

1429 verbose stack Error: unicode@0.6.1 postinstall: `node install.js`
1429 verbose stack Exit status 1
1429 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
1429 verbose stack     at emitTwo (events.js:106:13)
1429 verbose stack     at EventEmitter.emit (events.js:191:7)
1429 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
1429 verbose stack     at emitTwo (events.js:106:13)
1429 verbose stack     at ChildProcess.emit (events.js:191:7)
1429 verbose stack     at maybeClose (internal/child_process.js:877:16)
1429 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
1430 verbose pkgid unicode@0.6.1
1431 verbose cwd c:\Users\xxxxxx\Downloads\snowflake
1432 error Windows_NT 6.1.7601
1433 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1434 error node v7.0.0
1435 error npm  v3.10.8
1436 error code ELIFECYCLE
1437 error unicode@0.6.1 postinstall: `node install.js`
1437 error Exit status 1
1438 error Failed at the unicode@0.6.1 postinstall script 'node install.js'.
1438 error Make sure you have the latest version of node.js and npm installed.
1438 error If you do, this is most likely a problem with the unicode package,
1438 error not with npm itself.
1438 error Tell the author that this fails on your system:
1438 error     node install.js
1438 error You can get information on how to open an issue for this project with:
1438 error     npm bugs unicode
1438 error Or if that isn't available, you can get their info via:
1438 error     npm owner ls unicode
1438 error There is likely additional logging output above.
1439 verbose exit [ 1, true ]

**Comment by bartonhammond** [comment]
I don't have Windows box to look at this.  Please try upgrading Snowflake: https://github.com/bartonhammond/snowflake/releases/tag/0.2.1 and try again.
