### ISSUE TITLE
react-native run-ios fails on mac

### ISSUE THREAD

**Issue by iSamuelBarney** [bartonhammond/snowflake#162]
[11/12/2016, 10:18:19 PM] <START> Building Dependency Graph
[11/12/2016, 10:18:19 PM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2016-11-12 22:18 node[3583] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1274:11)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
~
Process terminated. Press <enter> to close the window

other terminal gives(at the same time):

Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Volumes/LaCie/sam.lacie/snowflake/ios/build/Build/Products/Debug-iphonesimulator/snowflake.app/PlugIns/snowflakeTests.xctest

** BUILD SUCCEEDED **

Installing build/Build/Products/Debug-iphonesimulator/snowflake.app
No devices are booted.
Launching mobi.snowflake.demo
No devices are booted.

I'm fairly new to using a mac with dev & react-native as well so please let me know if I'm missing something keep in mind I followed the install instructions correctly...

git clone
npm install 
cp config.js
react-native run-ios // also the test command works and says I should have no errors and everything passed.... please help SOS

**Comment by bartonhammond** [comment]
What version of xcode do you have?  I'm on 7.3.1

You could install Genymotion and set up an Anroid environment to confirm it
works.

**Comment by bartonhammond** [comment]
Yeah, I'm not up to xcode 8.  If you figure it out, consider a PR.

**Comment by iSamuelBarney** [comment]
I'm looking @ https://github.com/facebook/react-native/issues/8108 relating to issues with react-native on xcode 8+ build fails... also I've fixed 1 of the 2 build fail errors so only 1 left. Will update if next fix works.

**Comment by bartonhammond** [comment]
Great.  I have limited band width so upgrading is difficult.

**Comment by iSamuelBarney** [comment]
Think I found it... issue with Sierra testing the workaround now. ref:https://github.com/facebook/react-native/issues/9309

**Comment by iSamuelBarney** [comment]
FYI, definitely was an issue with watching files or some limit that applies to Sierra using react-native I actually didn't use the workaround above although I might at some point. The fix for me was:

`installing brew
brew install watchman`

I guess watchman does a good job at handling watching that many files in Sierra so the error is gone now and it works.. hmm. Thanks so much for the help @bartonhammond looking forward to using this project on our next release in the app store so happy to get it working.

**Comment by bartonhammond** [comment]
So xcode 8 requires update of osx?

**Comment by iSamuelBarney** [comment]
Xcode 8+ requires brew watchman or https://github.com/facebook/react-native/issues/9309 workaround to run react-native run-ios is the take away from this

**Comment by riccitensor** [comment]
Having the same, but https://github.com/facebook/react-native/issues/9309 helps.
