### ISSUE TITLE
some tests fail: SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by joshblour** [bartonhammond/snowflake#38]
When cloning from master and running the tests, 4 test suites fail with errors similar to this one:
```
FAIL  src/components/__tests__/ItemCheckbox-test.js 
● Runtime Error
Error: Failed to get mock metadata: /Users/Yonah/development/react/snowflake_2/node_modules/react/lib/canDefineProperty.js
    at Loader._generateMock (/Users/Yonah/development/react/snowflake_2/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:251:15)
    at Loader.requireMock (/Users/Yonah/development/react/snowflake_2/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:677:45)
    at Loader.requireModuleOrMock (/Users/Yonah/development/react/snowflake_2/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:788:19)
    at Object.eval (/Users/Yonah/development/react/snowflake_2/node_modules/react/lib/ReactElement.js:17:25)
    at Loader._execModule (/Users/Yonah/development/react/snowflake_2/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:206:17)
    at Loader.requireModule (/Users/Yonah/development/react/snowflake_2/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:760:14)
    at Loader._generateMock (/Users/Yonah/development/react/snowflake_2/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:243:34)
    at Loader.requireMock (/Users/Yonah/development/react/snowflake_2/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:677:45)
    at Loader.requireModuleOrMock (/Users/Yonah/development/react/snowflake_2/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:788:19)
    at Object.eval (/Users/Yonah/development/react/snowflake_2/node_modules/react/lib/ReactMount.js:18:20)
````
is this related to #29 or #11?

**Comment by bartonhammond** [comment]
yes, #29 is the problem 

If you run the tests as 

```
npm test src/reducers
```
you'll get all success
