### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by perqa** [bartonhammond/snowflake#50]
Following the instructions for initial setup, and trying to build, results in an exception for both Android and iOS:

```
react-native run-android

/Users/xyz/Workspace/ReactNative/snowflake/node_modules/react-native/local-cli/cli.js:73
  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xyz/Workspace/ReactNative/snowflake/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/xyz/Workspace/ReactNative/snowflake/node_modules/react-native/cli.js:15:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

The following displays in a Terminal window which pops up when opening the iOS project in Xcode:
```
~/Workspace/ReactNative/snowflake/node_modules/react-native/packager ~

/Users/xyz/Workspace/ReactNative/snowflake/node_modules/react-native/local-cli/cli.js:73
  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
~
Process terminated. Press <enter> to close the window
```

**Comment by bartonhammond** [comment]
I upgrade Snowflake and did not see this problem.  Please upgrade to newest release: [https://github.com/bartonhammond/snowflake/releases/tag/0.0.10a](https://github.com/bartonhammond/snowflake/releases/tag/0.0.10a)

**Comment by perqa** [comment]
The problem remains for me, even after update, but I guess it must be an environment problem then...?

**Comment by bartonhammond** [comment]
@perqa did you do a fresh checkout?

**Comment by perqa** [comment]
The problem was my Node version was too old. I got the same error for AwesomeProject in the FB guide. Updated nvm, node and npm, and can now build AwesomeProject, but get the following error for Snowflake:

Error building DependencyGraph:
 Error: Naming collision detected: /Users/perqa/Workspace/ReactNative/snowflake/node_modules/fbjs/lib/warning.js collides with /Users/perqa/Workspace/ReactNative/snowflake/node_modules/react/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/perqa/Workspace/ReactNative/snowflake/node_modules/promise/lib/core.js:37:12)
    at /Users/perqa/Workspace/ReactNative/snowflake/node_modules/promise/lib/core.js:123:15
    at flush (/Users/perqa/Workspace/ReactNative/snowflake/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
~
Process terminated. Press <enter> to close the window

**Comment by bartonhammond** [comment]
You need to read the release notes: [https://github.com/bartonhammond/snowflake/releases/tag/0.0.10](https://github.com/bartonhammond/snowflake/releases/tag/0.0.10) - namely that you'll have to 

* ```npm install -g npm3```
*  ```rm -rf node_modules``` 
*  ```npm3 install```

**Comment by perqa** [comment]
Sorry, I did update to npm3, but forgot the 
```
rm -rf node_modules
``` 

I have successfully built the iOS app, but there is still some trouble at the mill:
![image](https://cloud.githubusercontent.com/assets/960796/12698632/2a3d31de-c7a2-11e5-8ec4-0203012df355.png)

**Comment by bartonhammond** [comment]
You need to make sure that you started the client 'react-native start' - and be sure you are in ```snowflake``` - if the client is running somewhere else, the app fails like what you see here

**Comment by perqa** [comment]
Fantastic! Manually giving the command
```
react-native start
```
made all the difference. Didn't see that in the tutorial...

Many thanks for all your help to get me started, a help which was far beyond my expectations. I'm really looking forward to exploring React Native and Snowflake further now. Thanks!

**Comment by bartonhammond** [comment]
It's a common mistake, I do it all the time as I install various projects to learn something and inevitably forget to restart.    Glad your like Snowflake - do me a favor and "Star" the project.  Let me know if you have any more issues/questions.  Good luck

**Comment by hchoriq** [comment]
I know this has been posted already but I can't for the life of me figure this out. It still keeps giving me the same error as above. I've tried npm3 install (and also making sure my nvm had switched to node 5.6 with npm 3+) and still giving me the use of const strict mode error. Also made sure I was running react-native start in snowflake dir.

Any other clues? Thanks.

  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/Untitled/test/snowflake/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Volumes/Untitled/test/snowflake/node_modules/react-native/cli.js:15:18)
    at Module._compile (module.js:460:26)
Command /bin/sh failed with exit code 1

**Comment by hchoriq** [comment]
Should mention AwesomeProject loads fine straight out of the box for me. Can't figure out what I'm doing wrong with snowflake?

**Comment by bartonhammond** [comment]
I don't think this is Snowflake specific.  This issue on RN seems to be what you're experiencing: [https://github.com/facebook/react-native/issues/3946](https://github.com/facebook/react-native/issues/3946)

**Comment by hchoriq** [comment]
Yes! nvm alias default v5.6.0 fixed it for me because it was referencing an old node version. I google'd the issue for over an hour and did not find that post, I apologize. Thank you for your reply - as always. This project gets as many stars as I'm allowed to give.
