### ISSUE TITLE
Error: Naming collision detected on latest code (31-Jan)

### ISSUE THREAD

**Issue by tinygipxy** [bartonhammond/snowflake#56]
I got this issue on console when click start app from xcode: 
[1:57:42 PM] <END>   Building (deprecated) Asset Map (2391ms)
Error building DependencyGraph:
 Error: Naming collision detected: /Users/supermac/Projects/snowflake/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/supermac/Projects/snowflake/node_modules/react-native/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/supermac/Projects/snowflake/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/supermac/Projects/snowflake/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/supermac/Projects/snowflake/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

**Comment by bartonhammond** [comment]
Please look at release notes, mainly to install nmp3 and running ```npm3 install``` after ```rm if node_modules```

**Comment by tinygipxy** [comment]
Thank you, just know there is release notes also, patched it and it works fine now
