### ISSUE TITLE
Cannot run app on iOS after following instructions

### ISSUE THREAD

**Issue by ndbroadbent** [bartonhammond/snowflake#94]
I'm seeing this error immediately after starting the app:

    Application snowflake has not been registered. This is either due to a require() error during initialization or failure to call.

Versions:

* npm: 3.8.6
* node: v6.0.0
* xcode: 7.3
* react-native-cli: 0.2.0
* react-native: 0.22.2

I removed and `brew install`ed everything from scratch (npm and node). It still might be something to do with my environment, though.

When I go to the 'snowflake' directory and run `npm start`, I am also seeing this output with an error:

```

> snowflake@0.0.14 start /Users/ndbroadbent/code/apps/snowflake
> react-native start

Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/ndbroadbent/.nvm/versions/node/v6.0.0/bin/node" "/Users/ndbroadbent/.nvm/versions/node/v6.0.0/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! snowflake@0.0.14 start: `react-native start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snowflake@0.0.14 start script 'react-native start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snowflake package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-native start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snowflake
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snowflake
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ndbroadbent/code/apps/snowflake/npm-debug.log
```

`react-native` is not installed globally, so this error message is wrong and not helpful at all.

If I change the start script to use a locally installed react-native-cli, then I get this error:

```
> snowflake@0.0.14 start /Users/ndbroadbent/code/apps/snowflake
> node node_modules/react-native/local-cli/cli.js start

 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/ndbroadbent/.nvm/versions/node/v6.0.0/bin/node" "/Users/ndbroadbent/.nvm/versions/node/v6.0.0/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! snowflake@0.0.14 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snowflake@0.0.14 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snowflake package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snowflake
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snowflake
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ndbroadbent/code/apps/snowflake/npm-debug.log
```

Any ideas on how I can fix this?

**Comment by ndbroadbent** [comment]
Also, when I run `npm test` I get these errors and failures:

```

> snowflake@0.0.14 test /Users/ndbroadbent/code/apps/snowflake
> rm -rf ./node_modules/jest-cli/.haste_cache && jest  --no-cache

Using Jest CLI v0.9.2, jasmine2, babel-jest
 FAIL  src/reducers/device/__tests__/deviceReducer-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/components/__tests__/FormButton-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/reducers/auth/__tests__/authActions-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/reducers/profile/__tests__/profileReducer-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/components/__tests__/LoginForm-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/components/__tests__/ItemCheckbox-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/reducers/auth/__tests__/authReducer-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/reducers/profile/__tests__/profileActions-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/components/__tests__/Header-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/components/__tests__/ErrorAlert-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
 FAIL  src/reducers/device/__tests__/deviceActions-test.js
Runtime Error
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at handle (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/ndbroadbent/code/apps/snowflake/node_modules/worker-farm/lib/child/index.js:47:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by ndbroadbent** [comment]
Sorry, this was a problem with 'nvm', which I didn't uninstall properly.
